site_name: JR-DOCS

theme:
  name: simple-blog
  highlightjs: true
    - yaml
    - bash
    - php
    - html
  admonition:
      <type>: <icon>
  sidebar: true
  navigation_depth: 3
  components:
    footer: false
  site_name_style: overline
  theme_style: light

docs_dir: src

extra_css:
  - stylesheets/extra.css

nav:
  - Home: breakdown/docs/documentation.md
  - Moodboard:
    - Moodboard: moodboard/docs/documentation.md
  - Location:
    - Location: location/docs/documentation.md
  - Equipment:
    - Equipment: equipment/docs/documentation.md
  - Costs:
    - Costs: costs/docs/documentation.md
  - Timetable:
    - Timetable: timetable/docs/documentation.md