site_name: JR-DOCS

theme:
  name: simple-blog
  highlightjs: true
    - yaml
    - bash
    - php
    - html
  admonition:
      <type>: <icon>
  sidebar: true
  navigation_depth: 3
  components:
    footer: false
  site_name_style: overline
  theme_style: light

docs_dir: src

markdown_extensions:
  - admonition

extra_css:
  - stylesheets/extra.css

nav:
  - Home: breakdown/docs/documentation.md
  - Moodboard: moodboard/docs/documentation.md
  - Location: location/docs/documentation.md
  - Equipment: equipment/docs/documentation.md
  - Costs: costs/docs/documentation.md
  - Timetable: timetable/docs/documentation.md